name: urbancart

services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
  
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5001:5000
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
