name: urbancart

services:

  api_gateway_service:
    build:
      context: ./api_gateway_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db
      - auth_service
      - user_service
    volumes:
      - ./api_gateway_service:/app
      - ./common:/app/common

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./auth_service:/app
      - ./common:/app/common
  
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./user_service:/app
      - ./common:/app/common
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
